services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
      - ollama
    environment:
      OLLAMA_HOST: http://ollama:11434
    network_mode: service:db
  
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpswd25
      POSTGRES_DB: llmcodespace
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
  
  # redis:
  #   image: "redis:alpine"
  #   environment:
  #     REDIS_PASSWORD: llmredis
  #   ports:
  #     - "6379:6379"
  #   command: ["redis-server", "--requirepass", "llmredis"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./volumes/qdrantdata:/qdrant/storage
  
  ollama:
    build:
      context: ..
      dockerfile: .devcontainer/ollama.Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama

# Named volumes are saved here. 
# Path volumes with `./` and binded to local directories
volumes:
  postgresdata:
  ollama_models:

